### ISSUE TITLE
line not documented properly

### ISSUE THREAD

**Issue by kattni** [adafruit/Adafruit_CircuitPython_Display_Shapes#21]
The `line` module is not added to the `api.rst` file, so RTD isn't rendering the documentation within it. This needs to be fixed.

@kmatch98 If you have time, please look into this. Feel free to ping me with questions if you have any.

**Comment by kmatch98** [comment]
@kattni.  I will take a look at this. 

I have no idea what a lot of those letters you wrote mean, but let me poke around a bit and I will strive to come up with a few intelligent questions.  :)

Running list:
RTD = ReadTheDocs documentation system

Sphinx = a system for generating documentation for Python code

https://brandons-sphinx-tutorial.readthedocs.io/en/latest/index.html

**Comment by kattni** [comment]
@kmatch98 I mistakenly thought you added the `line` module because your PR was the most recently merged. You're still welcome to look into this, but I should tag the original author as well so they know for future reference. If you're not comfortable sorting this out, we can defer to her to get it fixed up. Let me know what you think.

@makermelissa Tagging you on this issue as you are the one who added the`line` module. May need you to step in to resolve the issue, but let kmatch98 let us know where they're at.

**Comment by kmatch98** [comment]
@kattni No worries. I recently added a different function (Sparkline) so it probably needs the same attention to the documentation. If you’re not in a hurry I will take a look at it and see if I can deal with `Line` and `Sparkline` at the same time. 

If you need it done promptly then I will leave it to @makermelissa and I will follow her lead.

**Comment by kattni** [comment]
@kmatch98 I'm not in a hurry. I'd rather encourage a learning opportunity than rush it. Let me know if/when you have questions!

**Comment by makermelissa** [comment]
Thanks @kattni, I probably forgot to add it to the api.rst file. I have a few minutes, so I can go in and fix this.
