### ISSUE TITLE
Polygon code fails when using on MatrixPortal M4

### ISSUE THREAD

**Issue by DeanDavis** [adafruit/Adafruit_CircuitPython_Display_Shapes#26]
Started to use this library on a 32x64 LED Matrix using the MatrixPortal M4
A simple line fails to render properly.

Example:
`Group.append(adafruit_display_shapes.line(0,0,2,2,0xFFFFFF))`

I would expect pixels (0,0), (1,1) & (2,2) to be white.
But only pixels (0,0) and (1,1) are lit.

In general one would always expect the beginning and ending pixels to be lit up every-time but this doesn't happen.

My cursory look at the code I think the bug appears in the polygon code.

The loop `for x in range(x0, x1):` where it attempts to color the bit map, range() doesn't include x1 in the range and x1 is the max value of all the x's passed into the polygon function.
So in my example x0=0, x2=2 so the `x` in the for loop never becomes 2 so pixel (2,2) will not become lit.

**Comment by makermelissa** [comment]
Ah yeah, I probably missed that when I was fixing a similar issue in #23.
