### ISSUE TITLE
self._x and self._y are unused

### ISSUE THREAD

**Issue by bablokb** [adafruit/Adafruit_CircuitPython_Display_Shapes#55]
The parameters x and y to the constructor are saved to self._x and self._y, but these variables are never used. Do I miss something here?
(x and y themselves are passed to the super-class).

**Comment by makermelissa** [comment]
Are you referring to the sparkline? Yeah it might be able to be removed from there. Want to test that it still works after removing and submit a PR?

**Comment by bablokb** [comment]
Yes, this is within the sparkline-constructor. I will remove those lines.

**Comment by tekktrik** [comment]
Closed via #56
