### ISSUE TITLE
CircuitPython v8.0.0-beta.2: display_shapes.polygon color fill is rendering very slowly

### ISSUE THREAD

**Issue by CedarGroveStudios** [adafruit/Adafruit_CircuitPython_Display_Shapes#57]
Compared to v7.3.3, polygon color fill during instantiation of the triangle display shape runs significantly slower in v8.0.0-beta.0. The rendering time for a filled triangle in v7.3.3 is about 1.8 seconds compared to 161 seconds in v8.0.0-beta.0. It also appears that the border fill is taking longer, 4.7 seconds versus 0.4 seconds. Also interesting that instantiating an object without a fill and border takes 25 times longer.

When pausing the execution during rendering, the trace shows that it's spending the majority of the time in `polygon.py`. I haven't had the opportunity to trace the issue further into the `polygon.py` code and hope that there may have been a recent change that could be reversed or corrected.

Here's the PyPortal Titano test code:

```python
import board
import time
import displayio
from adafruit_display_shapes.triangle import Triangle

display = board.DISPLAY
#triangle_group = displayio.Group()

width = display.width
height = display.height
print(f"width: {width}  height: {height}")

t0 = time.monotonic()
print("triangle_1: ", end="")
triangle_1 = Triangle(
    width,
    height,
    0,
    0,
    0,
    height,
    fill=None,
    outline=None,
)
print(time.monotonic() - t0)

t0 = time.monotonic()
print("triangle_2: ", end="")
triangle_2 = Triangle(
    width,
    height,
    0,
    0,
    0,
    height,
    fill=0x111111,
    outline=None,
)
print(time.monotonic() - t0)

t0 = time.monotonic()
print("triangle_3: ", end="")
triangle_3 = Triangle(
    width,
    height,
    0,
    0,
    0,
    height,
    fill=None,
    outline=0x111111,
)
print(time.monotonic() - t0)
```
The 7.3.3 results:
```python
Adafruit CircuitPython 7.3.3 on 2022-08-29; Adafruit PyPortal Titano with samd51j20
>>> 

code.py output:

width: 480  height: 320
triangle_1: 0.0019989
triangle_2: 1.771
triangle_3: 0.410995
```

The 8.0.0-beta.0 results:

```python
Adafruit CircuitPython 8.0.0-beta.0 on 2022-08-18; Adafruit PyPortal Titano with samd51j20
>>> 

code.py output:
]0;🐍code.py | 8.0.0-beta.0\
width: 480  height: 320
triangle_1: 0.0507813
triangle_2: 161.438
triangle_3: 4.66797
```

**Comment by tekktrik** [comment]
@dhalbert @jepler not sure if you saw this, not sure if you saw this, but thought you'd be interested

**Comment by tammymakesthings** [comment]
Tested on a PyBadge, and I got these results:

**CP 8.0.0-beta.0:**
```
width: 160  height: 128
triangle_1: 0.000999451
triangle_2: 0.234
triangle_3: 0.066
```

**CP 7.3.3:**
```
width: 160  height: 128
triangle_1: 0.0010004
triangle_2: 0.241
triangle_3: 0.0710001
```
Could this be something specific to the PyPortal? I can't find my PyPortal board right now to do further testing.

**Comment by FoamyGuy** [comment]
Very odd. I tried it out on the standard pyportal in a few versions and got roughly the same results on all of them. I'll try the Titano next, maybe it could be something specific to that.

```
Adafruit CircuitPython 7.3.1 on 2022-06-22; Adafruit PyPortal with samd51j20

code.py output:
width: 320  height: 240
triangle_1: 0.0010376
triangle_2: 0.853027
triangle_3: 0.205994
```

```
Adafruit CircuitPython 7.3.3 on 2022-08-29; Adafruit PyPortal with samd51j20
code.py output:
width: 320  height: 240
triangle_1: 0.0019989
triangle_2: 0.860001
triangle_3: 0.206001
```

```
Adafruit CircuitPython 8.0.0-beta.0 on 2022-08-18; Adafruit PyPortal with samd51j20
code.py output:
width: 320  height: 240
triangle_1: 0.00100708
triangle_2: 0.859009
triangle_3: 0.207001
```

**Comment by rsbohn** [comment]
7.3.0-beta.2 on 2022-04-27 Adafruit Feather M4 Express with samd51j19
width: 320  height: 240
triangle_1: 0.00109863
triangle_2: 0.668945
triangle_3: 0.026001

8.0.0-beta.0-40-g6a06a2d65 on 2022-09-10 Adafruit Feather M4 Express with samd51j19
width: 320  height: 240
triangle_1: 0.0019989
triangle_2: 0.655003
triangle_3: 0.0259972

**Comment by rsbohn** [comment]
8.0.0-beta.0 on 2022-08-18 Adafruit Feather M4 Express with samd51j19
width: 320  height: 240
triangle_1: 0.000999451
triangle_2: 0.649002
triangle_3: 0.0240021

**Comment by FoamyGuy** [comment]
With PyPortal Titano I was able to recreate the issue observed. 
```
Adafruit CircuitPython 7.3.3 on 2022-08-29; Adafruit PyPortal Titano with samd51j20

code.py output:
width: 480  height: 320
triangle_1: 0.00200272
triangle_2: 1.78
triangle_3: 0.413998
```

```
Adafruit CircuitPython 8.0.0-beta.0 on 2022-08-18; Adafruit PyPortal Titano with samd51j20
code.py output:
width: 480  height: 320
triangle_1: 0.052002
triangle_2: 162.996
triangle_3: 4.70599

```

**Comment by FoamyGuy** [comment]
Bisecting builds on the Titano I have found this this is the first commit build where the shapes become slow to initialize with:

[adafruit-circuitpython-pyportal_titano-en_US-20220810-7a5d2e8.uf2](https://adafruit-circuit-python.s3.amazonaws.com/bin/pyportal_titano/en_US/adafruit-circuitpython-pyportal_titano-en_US-20220810-7a5d2e8.uf2)

output from this build:
```
code.py output:
width: 480  height: 320
triangle_1: 0.0019989
triangle_2: 163.479
triangle_3: 4.71802
```



The build before it does not exhibit the same issue, it initializes the shapes quickly.
[adafruit-circuitpython-pyportal_titano-en_US-20220810-a1d48e9.uf2](https://adafruit-circuit-python.s3.amazonaws.com/bin/pyportal_titano/en_US/adafruit-circuitpython-pyportal_titano-en_US-20220810-a1d48e9.uf2)

output from this build:

```
code.py output:
width: 480  height: 320
triangle_1: 0.00200653
triangle_2: 1.338
triangle_3: 0.0309982
```

**Comment by dhalbert** [comment]
> Bisecting builds on the Titano I have found this this is the first commit build where the shapes become slow to initialize with:

Are you able to use `git bisect` to track down the exact commit?

**Comment by FoamyGuy** [comment]
@dhalbert I don't think I've used the git cli bisect before. I will give it a try later today to see if it can help narrow it further. 

From just trying different ones on S3 it's looking like this may be the commit that is affecting it. Nothing really jumps out as problematic to me, but it is changing stuff related to displays so I guess it may be interacting different with something about this device compared to others.

**Comment by gamblor21** [comment]
I hooked up a Feather M4 with the 320x480 TFT (product 2050) which is almost identical to the Titano.

With setting the `backlight_pin` and `backlight_pwm_frequency` so I could change them any frequency less then approximately 1000Hz the drawing slows. A frequency even barely about 1000 (1020) the display is slightly slowed but at 1000 it goes up to 30seconds (1020Hz was 2.3seconds).

I tried to duplicate the PyPortal pins as close as I could on the feather.

`display_bus = displayio.ParallelBus(data0=board.D5, command=board.A1, chip_select=board.A0, write=board.A2, read=board.A3, reset=board.A4)`
`display = HX8357(display_bus, width=480, height=320, backlight_pin=board.RX, backlight_pwm_frequency=1000)`

**Comment by CedarGroveStudios** [comment]
A non-conclusive data point: To isolate the hardware, I released the display and took control of the TFT backlight (thanks to a suggestion by @todbot). With no display selected, the backlight frequency had no appreciable impact.

```python
import board
import time
import displayio
import os
import pwmio
from adafruit_display_shapes.triangle import Triangle

displayio.release_displays()
display = board.DISPLAY

tft_backlight = pwmio.PWMOut(board.TFT_BACKLIGHT, frequency=50000, duty_cycle = 2**15)
tft_backlight.duty_cycle = 65535 // 2  # turn on 50%

print(os.uname()[3], os.uname()[4])

width = 480
height = 320

print(f"width: {width}  height: {height}  backlight: {tft_backlight.frequency} Hz")

t0 = time.monotonic()
print("triangle_1: ", end="")
triangle_1 = Triangle(
    width,
    height,
    0,
    0,
    0,
    height,
    fill=None,
    outline=None,
)
print(time.monotonic() - t0)

t0 = time.monotonic()
print("triangle_2: ", end="")
triangle_2 = Triangle(
    width,
    height,
    0,
    0,
    0,
    height,
    fill=0x111111,
    outline=None,
)
print(time.monotonic() - t0)

t0 = time.monotonic()
print("triangle_3: ", end="")
triangle_3 = Triangle(
    width,
    height,
    0,
    0,
    0,
    height,
    fill=None,
    outline=0x111111,
)
print(time.monotonic() - t0)

print("test completed")

while True:
    pass
```

```
7.3.3 on 2022-08-29 Adafruit PyPortal Titano with samd51j20
width: 480  height: 320  backlight: 50000 Hz
triangle_1: 0.0019989
triangle_2: 1.364
triangle_3: 0.0289917
test completed

7.3.3 on 2022-08-29 Adafruit PyPortal Titano with samd51j20
width: 480  height: 320  backlight: 500 Hz
triangle_1: 0.00198364
triangle_2: 1.36401
triangle_3: 0.0289917
test completed


]0;🐍code.py | 8.0.0-beta.0\8.0.0-beta.0 on 2022-08-18 Adafruit PyPortal Titano with samd51j20
width: 480  height: 320  backlight: 50000 Hz
triangle_1: 0.00195313
triangle_2: 1.28394
triangle_3: 0.0270996
test completed

]0;🐍code.py | 8.0.0-beta.0\8.0.0-beta.0 on 2022-08-18 Adafruit PyPortal Titano with samd51j20
width: 480  height: 320  backlight: 500 Hz
triangle_1: 0.00195313
triangle_2: 1.28394
triangle_3: 0.0290527
test completed
```

**Comment by CedarGroveStudios** [comment]
Also confirmed that although it doesn't error when setting, the `display.brightness` parameter is fixed at 1.0.

If the 500Hz backlight PWM throttle of the drawing rate is noticeable, could it be that when set to 50kHz, it’s still negatively impacting the drawing rate? Is it possible that, since it’s set to 50kHz for other boards, it’s having a broader impact than just the Titano?

**Comment by gamblor21** [comment]
Couple notes as I work away on this:
1. If I do not set the backlight in the display object and connect the light pin to my own PWM object things work as expected.
2. Setting the brightness does not work. This is strange as a quick glance at the code it should work. If I create a PWM object myself (the same the C code should be creating) it works.
3. There may be something to @CedarGroveStudios' thought that the PWM may be slowing other devices but haven't tested that.

**Comment by CedarGroveStudios** [comment]
Just tested this with -beta.4 and both the object drawing and Titano display brightness linearity issues are fixed. Test results:

```python
code.py output:
]0;🐍code.py | 8.0.0-beta.4\8.0.0-beta.4 on 2022-10-30 Adafruit PyPortal Titano with samd51j20
width: 480  height: 320
triangle_1: 0.0010376
triangle_2: 1.771
triangle_3: 0.39801
test completed
```

Thanks to all who pursued and fixed this issue.
